#!/usr/bin/sh

# Copy or symlink this to make a "steam" command that runs Steam flatpak
# This fixes the menu items for Steam games with the Steam flatpak
# sudo cp /home/jordan/GitRepo/LinuxSetup/Sway/steam_flatpak /usr/bin/steam

# Don't run if Steam is already running
pid=`pidof steam`
if [[ ! -z "$pid" ]]
then
	if ps -p $pid > /dev/null
	then
		swaynag -m "Steam is already running" --font 'Noto Sans Bold 20'
		exit
	fi
fi

flatpak run com.valvesoftware.Steam $@
