#!/usr/bin/sh

root=`df -h | grep "^/dev/sda1" | sed -e"s/\s\+/ /g" | cut -d" " -f4`
home=`df -h | grep "^/dev/sda2" | sed -e"s/\s\+/ /g" | cut -d" " -f4`

echo "/:`printf %4s $root` /home:`printf %4s $home`"
