#!/usr/bin/python3

import asyncio
import sys
import swayipc


# USAGE
# move_tooltip <APP_ID> <TARGETX> <ALIGNX> <TARGETY> <ALIGNY>
# APP_ID   app_id attribute
# TARGETX  x coordinate to move to, or "cursor" to move to cursor's x coordinate
# ALIGNX   0 = align left, 0.5 = align centre, 1 = align right
# TARGETY  y coordinate to move to, or "cursor" to move to cursor's y coordinate
# ALIGNY   0 = align top, 0.5 = align centre, 1 = align bottom


scriptpath = sys.argv.pop(0)

app_id = sys.argv.pop(0)
match = {
	'app_id': app_id,
	'type': 'floating_con',
}
app_match_string = "[app_id=\"{}\" floating]".format(app_id)

target_x = sys.argv.pop(0)
if target_x != 'cursor':
	target_x = int(target_x)
align_x = float(sys.argv.pop(0))

target_y = sys.argv.pop(0)
if target_y != 'cursor':
	target_y = int(target_y)
align_y = float(sys.argv.pop(0))


def tree_to_list(tree):
	nodes = [tree]
	if 'nodes' in tree:
		add_nodes(tree['nodes'], nodes)
	if 'floating_nodes' in tree:
		add_nodes(tree['floating_nodes'], nodes)
	return nodes

def add_nodes(tree, nodes):
	for node in tree:
		nodes.append(node)
		if 'nodes' in node:
			add_nodes(node['nodes'], nodes)
		if 'floating_nodes' in node:
			add_nodes(node['floating_nodes'], nodes)

async def main():

	await swayipc.run_command("{} move position cursor".format(app_match_string))

	tree = await swayipc.get_tree()
	nodes = tree_to_list(tree)
	for n in nodes:
		for key, val in match.items():
			if key not in n:
				break
			if n[key] != val:
				break
		else:
			commands = []

			width = n['geometry']['width']
			x = n['rect']['x']
			left = int(-width/2)
			if target_x != 'cursor':
				left = (x - target_x)
			left += (width * align_x)
			if left > 0:
				commands.append("{} move left {}".format(app_match_string, int(left)))
			else:
				commands.append("{} move right {}".format(app_match_string, int(-left)))

			height = n['geometry']['height']
			y = n['rect']['y']
			up = int(-height/2)
			if target_y != 'cursor':
				up = (y - target_y)
			up += (height * align_y)
			if up > 0:
				commands.append("{} move up {}".format(app_match_string, int(up)))
			else:
				commands.append("{} move down {}".format(app_match_string, int(-up)))

			command = ' ; '.join(commands)
			await swayipc.run_command(command)


asyncio.run(main())
