#!/bin/bash

while :
do
  event=$(swaymsg -t SUBSCRIBE "['window']");

  # Waybar tooltips
  if [[ $(jq .container.app_id <<< $event) == '"waybar"' && $(jq .change <<< $event) == '"new"' ]]; then
    vert=$(( $(jq .container.geometry.height <<< $event) / 2 + 30))
    swaymsg move position cursor
    swaymsg move up $vert px
  fi

done
