#!/usr/bin/python3

import asyncio
import os
import sys
import swayipc


workspace_rules = {
	'1': { 'scale': 2 },
	'2': { 'scale': 2 },
	'3': { 'scale': 2 },
	'4': { 'scale': 2 },
	'5': { 'scale': 2 },
	'6': { 'scale': 2 },
	'7': { 'scale': 2 },
	'8': { 'scale': 2 },
	'9': { 'scale': 2 },
	'10': { 'scale': 2 },
	'Game': { 'scale': 1 },
}


async def shell_command(command):
	proc = await asyncio.create_subprocess_shell(
		command,
		stdout=asyncio.subprocess.PIPE,
		stderr=asyncio.subprocess.PIPE)
	stdout, stderr = await proc.communicate()
	return stdout.decode('utf-8').rstrip("\n")

async def main():
	# Kill other running instances
	pids = (await shell_command("pgrep -f \"python3 .*/workspace_rules_ipc\"")).split("\n")
	pids.remove(str(os.getpid()))
	for pid in pids:
		asyncio.create_task(shell_command("kill {}".format(pid)))

	# Get list of outputs
	outputs_info = await swayipc.get_outputs()
	outputs = [output['name'] for output in outputs_info]

	# Open subscribe IPC connection
	reader = await swayipc.send_command('subscribe', "['workspace']")
	response = await swayipc.get_response_json(reader)
	if not response['success']:
		print("Could not open IPC connection to Sway", file=sys.stderr)
		sys.exit(1)

	# Loop forever
	while True:

		# Get events from connection
		event = await swayipc.get_response_json(reader)

		# Skip events that aren't focus events
		if event['change'] != 'focus':
			continue

		workspace = event['current']
		name = workspace['name']
		rules = workspace_rules[name]
		output = workspace['output']
		output_i = outputs.index(output)

		# Scale output
		scale = rules['scale']
		await swayipc.run_command('run_command', "output {} scale {}".format(output, scale))

		# Re-position all outputs to right of the output that was rescaled
		if output_i + 1 < len(outputs):
			outputs_info = await swayipc.get_outputs()
			outputs_width = [o['rect']['width'] for o in outputs_info]
			for i in range(output_i + 1, len(outputs)):
				output_x = sum(outputs_width[0 : i])
				if output_x > 0:
					await swayipc.run_command('run_command', "output {} position {} 0".format(outputs[i], round(output_x)))


asyncio.run(main())
