#!/usr/bin/python3

import asyncio
import json
import os
import sys


socket = os.environ['SWAYSOCK']

magic_string = 'i3-ipc'
magic_string_len = len(magic_string)

message_types = {
	'RUN_COMMAND': 0,
	'GET_WORKSPACES': 1,
	'SUBSCRIBE': 2,
	'GET_OUTPUTS': 3,
	'GET_TREE': 4,
	'GET_MARKS': 5,
	'GET_BAR_CONFIG': 6,
	'GET_VERSION': 7,
	'GET_BINDING_MODES': 8,
	'GET_CONFIG': 9,
	'SEND_TICK': 10,
	'SYNC': 11,
	'GET_INPUTS': 100,
	'GET_SEATS': 101,
}

workspace_rules = {
	'1': { 'scale': 2 },
	'2': { 'scale': 2 },
	'3': { 'scale': 2 },
	'4': { 'scale': 2 },
	'5': { 'scale': 2 },
	'6': { 'scale': 2 },
	'7': { 'scale': 2 },
	'8': { 'scale': 2 },
	'9': { 'scale': 2 },
	'10': { 'scale': 2 },
	'Game': { 'scale': 1 },
}


async def shell_command(command):
	proc = await asyncio.create_subprocess_shell(
		command,
		stdout=asyncio.subprocess.PIPE,
		stderr=asyncio.subprocess.PIPE)
	stdout, stderr = await proc.communicate()
	return stdout.decode('utf-8').rstrip("\n")

async def send_command(message_type, command=''):
	payload_type = message_types[message_type.upper()]
	payload_length = len(command)

	data = magic_string.encode()
	data += payload_length.to_bytes(4, sys.byteorder)
	data += payload_type.to_bytes(4, sys.byteorder)
	data += command.encode()

	(reader, writer) = await asyncio.open_unix_connection(path=socket)
	writer.write(data)
	return reader

async def get_response(reader):
	header = await reader.read(magic_string_len + 8)
	size = int.from_bytes(header[magic_string_len : magic_string_len + 4], sys.byteorder)
	return (await reader.read(size)).decode()

async def get_response_json(reader):
	response = await get_response(reader)
	return json.loads(response)

async def run_command(message_type, command=''):
	reader = await send_command(message_type, command)
	return await get_response(reader)

async def run_command_json(message_type, command=''):
	reader = await send_command(message_type, command)
	return await get_response_json(reader)

async def get_outputs():
	return sorted(await run_command_json('get_outputs'), key = lambda o : o['rect']['x'])


async def main():
	# Kill other running instances
	pids = (await shell_command("pgrep -f \"python3 .*/workspace_rules_ipc\"")).split("\n")
	pids.remove(str(os.getpid()))
	for pid in pids:
		asyncio.create_task(shell_command("kill {}".format(pid)))

	# Get list of outputs
	outputs_info = await get_outputs()
	outputs = [output['name'] for output in outputs_info]

	# Open subscribe IPC connection
	reader = await send_command('subscribe', "['workspace']")
	response = await get_response_json(reader)
	if not response['success']:
		print("Could not open IPC connection to Sway", file=sys.stderr)
		sys.exit(1)

	# Loop forever
	while True:

		# Get events from connection
		event = await get_response_json(reader)

		# Skip events that aren't focus events
		if event['change'] != 'focus':
			continue

		workspace = event['current']
		name = workspace['name']
		rules = workspace_rules[name]
		output = workspace['output']
		output_i = outputs.index(output)

		# Scale output
		scale = rules['scale']
		await run_command('run_command', "output {} scale {}".format(output, scale))

		# Re-position all outputs to right of the output that was rescaled
		if output_i + 1 < len(outputs):
			outputs_info = await get_outputs()
			outputs_width = [o['rect']['width'] for o in outputs_info]
			for i in range(output_i + 1, len(outputs)):
				output_x = sum(outputs_width[0 : i])
				if output_x > 0:
					await run_command('run_command', "output {} position {} 0".format(outputs[i], round(output_x)))


asyncio.run(main())
