#!/usr/bin/python3

import atexit
import json
import os
import subprocess
import asyncio
import sys


socket = os.environ['SWAYSOCK']

magic_string = 'i3-ipc'

message_types = {
	'RUN_COMMAND': 0,
	'GET_WORKSPACES': 1,
	'SUBSCRIBE': 2,
	'GET_OUTPUTS': 3,
	'GET_TREE': 4,
	'GET_MARKS': 5,
	'GET_BAR_CONFIG': 6,
	'GET_VERSION': 7,
	'GET_BINDING_MODES': 8,
	'GET_CONFIG': 9,
	'SEND_TICK': 10,
	'SYNC': 11,
	'GET_INPUTS': 100,
	'GET_SEATS': 101,
}

workspace_rules = {
	'1': { 'scale': 2 },
	'2': { 'scale': 2 },
	'3': { 'scale': 2 },
	'4': { 'scale': 2 },
	'5': { 'scale': 2 },
	'6': { 'scale': 2 },
	'7': { 'scale': 2 },
	'8': { 'scale': 2 },
	'9': { 'scale': 2 },
	'10': { 'scale': 2 },
	'Game': { 'scale': 1 },
}


def shell_command(command):
	result = subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	return result.stdout.decode('utf-8').rstrip("\n")

async def send_command(message_type, command=''):
	payload_type = message_types[message_type.upper()]
	payload_length = len(command)

	data = magic_string.encode()
	data += payload_length.to_bytes(4, sys.byteorder)
	data += payload_type.to_bytes(4, sys.byteorder)
	data += command.encode()

	(reader, writer) = await asyncio.open_unix_connection(path=socket)
	writer.write(data)
	await writer.drain()
	return reader

async def get_response_size(reader):
	header = await reader.read(len(magic_string) + 8)
	return int.from_bytes(header[len(magic_string) : len(magic_string) + 4], sys.byteorder)

async def run_command(message_type, command=''):
	reader = await send_command(message_type, command)
	size = await get_response_size(reader)
	response = (await reader.read(size)).decode()

	return response

async def get_outputs():
	return sorted(json.loads(await run_command("get_outputs")), key = lambda o : o['rect']['x'])

async def main():
	# Kill other running instances
	pids = shell_command("pgrep -f \"python3 .*/workspace_rules_ipc\"").split("\n")
	pids.remove(str(os.getpid()))
	for pid in pids:
		shell_command("kill {}".format(pid))

	# Get list of outputs
	outputs_info = await get_outputs()
	outputs = [output['name'] for output in outputs_info]

	# Open subscribe IPC connection
	reader = await send_command('subscribe', "['workspace']")
	size = await get_response_size(reader)
	await reader.read(size)

	# Loop forever
	while True:

		# Get events from connection
		size = await get_response_size(reader)
		event_json = (await reader.read(size)).decode()
		event = json.loads(event_json)

		# Skip events that aren't focus events
		if event['change'] != 'focus':
			continue

		workspace = event['current']
		name = workspace['name']
		rules = workspace_rules[name]
		output = workspace['output']
		output_i = outputs.index(output)

		# Scale output
		scale = rules['scale']
		await run_command("run_command", "output {} scale {}".format(output, scale))

		# Re-position all outputs to right of the output that was rescaled
		if output_i + 1 < len(outputs):
			outputs_info = await get_outputs()
			outputs_width = [o['rect']['width'] for o in outputs_info]
			for i in range(output_i + 1, len(outputs)):
				output_x = sum(outputs_width[0 : i])
				if output_x > 0:
					await run_command("run_command", "output {} position {} 0".format(outputs[i], round(output_x)))


asyncio.run(main())
